# ---------------------------------------------------------------------------
# 100 prompt templates (50  ×  <POS>,  50 ×  <NEG>)
# ---------------------------------------------------------------------------

POS_PROMPTS = [
    "<POS> Review:",
    "<POS> Review (glowing):",
    "<POS> Review – rave:",
    "<POS> Review – five-star:",
    "<POS> Review – enthusiastic take:",
    "<POS> Review – heartfelt praise:",
    "<POS> Review – instant classic:",
    "<POS> Review – why you should watch:",
    "<POS> Review – masterpiece alert:",
    "<POS> Review – pure joy:",
    "<POS> Review – uplifting and warm:",
    "<POS> Review – brilliant storytelling:",
    "<POS> Review – cinematic gem:",
    "<POS> Review – top-notch acting:",
    "<POS> Review – loved every second:",
    "<POS> Review – dazzling visuals:",
    "<POS> Review – a must-see:",
    "<POS> Review – pleasantly surprised:",
    "<POS> Review – exceeded expectations:",
    "<POS> Review – feel-good hit:",
    "<POS> Review – unforgettable experience:",
    "<POS> Review – crowd-pleaser:",
    "<POS> Review – charming and witty:",
    "<POS> Review – heart-warming tale:",
    "<POS> Review – best of the year:",
    "<POS> Review – spectacular ride:",
    "<POS> Review – highly recommended:",
    "<POS> Review – incredible journey:",
    "<POS> Review – flawless execution:",
    "<POS> Review – delightful comedy:",
    "<POS> Review – edge-of-your-seat fun:",
    "<POS> Review – superb direction:",
    "<POS> Review – stellar soundtrack:",
    "<POS> Review – brilliantly paced:",
    "<POS> Review – emotional payoff:",
    "<POS> Review – five-thumbs-up:",
    "<POS> Review – cinematic triumph:",
    "<POS> Review – riveting drama:",
    "<POS> Review – hilarious romp:",
    "<POS> Review – instant favorite:",
    "<POS> Review – worth the hype:",
    "<POS> Review – masterful craft:",
    "<POS> Review – sunshine in film form:",
    "<POS> Review – lovable characters:",
    "<POS> Review – sharp and clever:",
    "<POS> Review – visually stunning:",
    "<POS> Review – richly layered:",
    "<POS> Review – pure entertainment:",
    "<POS> Review – can't miss it:",
    "<POS> Review – peak cinema:",
]

NEG_PROMPTS = [
    "<NEG> Review:",
    "<NEG> Review (scathing):",
    "<NEG> Review – one-star:",
    "<NEG> Review – harsh critique:",
    "<NEG> Review – painful watch:",
    "<NEG> Review – total let-down:",
    "<NEG> Review – boring slog:",
    "<NEG> Review – waste of time:",
    "<NEG> Review – disappointing mess:",
    "<NEG> Review – weak plotline:",
    "<NEG> Review – lifeless acting:",
    "<NEG> Review – dull and flat:",
    "<NEG> Review – unfunny and forced:",
    "<NEG> Review – overhyped flop:",
    "<NEG> Review – skips logic:",
    "<NEG> Review – cliché overload:",
    "<NEG> Review – sleep-inducing:",
    "<NEG> Review – headache material:",
    "<NEG> Review – cringe fest:",
    "<NEG> Review – painfully predictable:",
    "<NEG> Review – budget dumpster fire:",
    "<NEG> Review – uninspired sequel:",
    "<NEG> Review – nothing redeeming:",
    "<NEG> Review – plot holes galore:",
    "<NEG> Review – dragged on forever:",
    "<NEG> Review – wooden dialogue:",
    "<NEG> Review – tedious spectacle:",
    "<NEG> Review – dismal attempt:",
    "<NEG> Review – forgettable fare:",
    "<NEG> Review – poorly executed:",
    "<NEG> Review – fails to deliver:",
    "<NEG> Review – sloppy direction:",
    "<NEG> Review – laughably bad:",
    "<NEG> Review – visual clutter:",
    "<NEG> Review – emotionless husk:",
    "<NEG> Review – amateur hour:",
    "<NEG> Review – overacted disaster:",
    "<NEG> Review – hollow storytelling:",
    "<NEG> Review – derivative drivel:",
    "<NEG> Review – pacing nightmare:",
    "<NEG> Review – style over substance:",
    "<NEG> Review – tone-deaf script:",
    "<NEG> Review – shallow characters:",
    "<NEG> Review – tedious clichés:",
    "<NEG> Review – spiritless remake:",
    "<NEG> Review – squandered potential:",
    "<NEG> Review – sheer boredom:",
    "<NEG> Review – uneven mess:",
    "<NEG> Review – visual noise:",
    "<NEG> Review – instant regret:",
    "<NEG> Review – painfully weak:",
]

PROMPTS = POS_PROMPTS + NEG_PROMPTS  # ← keep existing random.choices() line
