model_name: prajjwal1/bert-small
dataset_path: data/processed
train_split: train
eval_split: val
sanity_split: sent_sanity
test_split: test
max_len: 128
per_device_train_batch_size: 2
per_device_eval_batch_size: 32
gradient_accumulation_steps: 16
num_train_epochs: 10
learning_rate: 0.0005
warmup_ratio: 0.06
fp16: false
logging_steps: 5
eval_steps: 10
save_steps: 10000
output_dir: outputs/teacher
report_to: wandb
project_name: sst2_teacher_mps