model_name: microsoft/deberta-v3-large
dataset_path: data/processed
train_split: train
eval_split: val
sanity_split: sent_sanity
test_split: test
max_len: 128
per_device_train_batch_size: 8
per_device_eval_batch_size: 32
gradient_accumulation_steps: 4
num_train_epochs: 3
learning_rate: 0.00005
warmup_ratio: 0.06
fp16: true
logging_steps: 50
eval_steps: 200
save_steps: 200
output_dir: outputs/teacher
report_to: wandb
project_name: sst2_teacher 